'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("frpGUI.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;FRPGUI&gt;
        '''  &lt;server&gt;
        '''  &lt;/server&gt;
        '''  &lt;client&gt;
        '''    &lt;config&gt;
        '''      &lt;name&gt;WinRemoteDesktop&lt;/name&gt;
        '''      &lt;proto&gt;TCP&lt;/proto&gt;
        '''      &lt;port&gt;3389&lt;/port&gt;
        '''      &lt;domain&gt;
        '''      &lt;/domain&gt;
        '''      &lt;issub&gt;1&lt;/issub&gt;
        '''      &lt;ip&gt;127.0.0.1&lt;/ip&gt;
        '''      &lt;rport&gt;3389&lt;/rport&gt;
        '''    &lt;/config&gt;
        '''    &lt;config&gt;
        '''      &lt;name&gt;LinuxSSH&lt;/name&gt;
        '''      &lt;proto&gt;TCP&lt;/proto&gt;
        '''      &lt;port&gt;22&lt;/port&gt;
        '''      &lt;domain&gt;
        '''      &lt;/domain&gt;
        '''      &lt;issub&gt;1&lt;/issub&gt;
        '''      &lt;ip&gt;127.0.0.1&lt;/ip&gt;
        '''      &lt;rport&gt;2000&lt;/rport&gt;
        '''    &lt;/config&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property frpc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("frpc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
